---
trigger:

  # Already default, but made explicit here
  branches:
    include: ["*"]

  # Ensure Azure triggers a build on a new tag
  # We use these for GitHub releases
  tags:
    include: ["*"]

  paths:
    # Do not trigger a build on changes at these paths
    exclude:
      - .gitignore
      - LICENSE
      - README.md


jobs:

  # -----------------------------------------------------------------------
  #
  # Test
  #
  # -----------------------------------------------------------------------

  - job: Ubuntu
    pool:
      vmImage: "ubuntu-16.04"  # Xenial
    strategy:
      matrix:
        Python27:
          python.version: "2.7"
        Python35:
          python.version: "3.5"
        Python36:
          python.version: "3.6"
        Python37:
          python.version: "3.7"

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "$(python.version)"
        displayName: "Use Python $(python.version)"

      - script: |
          pip install bleeding_rez nose2 setuptools
        displayName: "pip install"

      - script: |
          rez bind --quickstart
          rez build --install
        displayName: "rez bind"

      - script: |
          nose2 --start-dir $(pwd)/python -vvv
        displayName: "test"


  - job: MacOS
    pool:
      vmImage: "macOS-10.13"  # High-Sierra
    strategy:
      matrix:
        Python27:
          python.version: "2.7"
        Python37:
          python.version: "3.7"

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "$(python.version)"
        displayName: "Use Python $(python.version)"

      - script: |
          pip install bleeding_rez nose2 setuptools
        displayName: "pip install"

      - script: |
          rez bind --quickstart
          rez build --install
        displayName: "rez bind"

      - script: |
          nose2 --start-dir $(pwd)/python -vvv
        displayName: "test"

  - job: Windows
    pool:
      vmImage: vs2017-win2016
    strategy:
      matrix:
        Python27:
          python.version: "2.7"
        Python37:
          python.version: "3.7"

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: "$(python.version)"
        displayName: "Use Python $(python.version)"
      - powershell: |
          pip install bleeding_rez nose2 setuptools
        displayName: "pip install"

      - powershell: |
          rez bind --quickstart
          rez build --install
        displayName: "rez bind"

      - powershell: |
          nose2 --start-dir=python -vvv
        displayName: "test"
